// SPDX-License-Identifier: Apache-2.0
#![allow(clippy::all, clippy::pedantic)]
#![allow(unexpected_cfgs)]

//! Laplace Probe SDK — support crate for the BYOC Phase 1 macro system.
//!
//! # Public API
//!
//! ```ignore
//! use laplace_probe_sdk::{TrackedMutex, ProbeSessionConfig};
//! ```
//!
//! # Internal API (generated-code only)
//!
//! ```ignore
//! use laplace_probe_sdk::{set_probe_sender, set_probe_thread_id};
//! ```

#[cfg(feature = "cloud")]
pub mod client;
pub mod config;
pub mod event;
pub mod license;
pub mod model_lock;
pub mod session;
pub mod tracked;
pub mod tracked_atomic;
#[cfg(feature = "parking_lot_tracking")]
pub mod tracked_parking_lot_rwlock;
pub mod tracked_rwlock;
pub mod tracked_semaphore;
pub mod tracked_std;
pub mod tracked_std_rwlock;

// ── 공개 재내보내기 ────────────────────────────────────────────────────────────

pub use config::{load_project_config, load_toml_max_depth, ProjectConfig};
pub use event::ProbeEvent;
pub use model_lock::{install_probe_lock_hook, ProbeLockHook};
pub use session::{
    clear_probe_sender, current_thread_id, dump_events_if_configured, emit, run_verification_from,
    set_probe_sender, set_probe_thread_id, CaptureSession, ProbeSessionConfig, ReferenceVerdict,
    VerifyResult,
};
pub use tracked::{TrackedGuard, TrackedMutex};
pub use tracked_atomic::{
    TrackedAtomicBool, TrackedAtomicU32, TrackedAtomicU64, TrackedAtomicUsize,
};
#[cfg(feature = "parking_lot_tracking")]
pub use tracked_parking_lot_rwlock::{
    TrackedParkingLotRwLock, TrackedParkingLotRwLockReadGuard, TrackedParkingLotRwLockWriteGuard,
};
pub use tracked_rwlock::{TrackedRwLock, TrackedRwLockReadGuard, TrackedRwLockWriteGuard};
pub use tracked_semaphore::{TrackedSemaphore, TrackedSemaphorePermit};
pub use tracked_std::{TrackedStdGuard, TrackedStdMutex};
pub use tracked_std_rwlock::{
    TrackedStdRwLock, TrackedStdRwLockReadGuard, TrackedStdRwLockWriteGuard,
};

#[cfg(feature = "cloud")]
pub use client::ProbeClientConfig;
#[cfg(feature = "cloud")]
pub use session::init_cloud_probe;

/// Stable import surface for code generated by `laplace-macro`.
///
/// This module is intentionally hidden from rendered docs. Public generated
/// macro output should depend on this path instead of individual root
/// re-exports so internal SDK organization can change without breaking users.
#[doc(hidden)]
pub mod __macro_support {
    pub use crate::ProbeEvent;
    pub use crate::{
        set_probe_sender, set_probe_thread_id, CaptureSession, ProbeSessionConfig, TrackedMutex,
        TrackedRwLock,
    };
    pub use tokio;
}
